esphome:
  name: sprinkler
  friendly_name: Sprinkler

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !key

ota:
  password: !pw
# mdns:
#   disabled: True
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # use_address: 192.168.0.0
  manual_ip:
      static_ip: 192.168.0.0
      gateway: 192.168.0.0
      subnet: 255.255.0.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinkler Fallback Hotspot"
    password: !wifi_pw

captive_portal:
    
switch:
  # Orange Cable
  - platform: gpio
    pin: GPIO16
    id: "sprinkler_middle"
    name: "Sprinkler Middle"
    on_turn_on: 
      then:
      # Make it so that only one channel can be on at once for power consuption reasons.
      # We don't want the voltage of the ESP to drop below about 4V since it could restart if too little power is available.
        - switch.turn_off: sprinkler_terrace
        - switch.turn_off: sprinkler_bed_middle
        - switch.turn_off: sprinkler_apple_tree
        - switch.turn_off: sprinkler_bamboo
        - switch.turn_off: sprinkler_drip
  # Green Cable
  - platform: gpio
    pin: GPIO5
    id: "sprinkler_terrace"
    name: "Sprinkler Terrace"
    on_turn_on: 
      then:
        - switch.turn_off: sprinkler_middle
        - switch.turn_off: sprinkler_bed_middle
        - switch.turn_off: sprinkler_apple_tree
        - switch.turn_off: sprinkler_bamboo
        - switch.turn_off: sprinkler_drip
  # Blue Cable
  - platform: gpio
    pin: GPIO4
    id: "sprinkler_bed_middle"
    name: "Sprinkler Bed Middle"
    on_turn_on: 
      then:
        - switch.turn_off: sprinkler_terrace
        - switch.turn_off: sprinkler_middle
        - switch.turn_off: sprinkler_apple_tree
        - switch.turn_off: sprinkler_bamboo
        - switch.turn_off: sprinkler_drip
  # Yellow Cable
  - platform: gpio
    pin: GPIO0
    id: "sprinkler_apple_tree"
    name: "Sprinkler Apple Tree"
    on_turn_on: 
      then:
        - switch.turn_off: sprinkler_terrace
        - switch.turn_off: sprinkler_bed_middle
        - switch.turn_off: sprinkler_middle
        - switch.turn_off: sprinkler_bamboo
        - switch.turn_off: sprinkler_drip
  # Red Cable
  - platform: gpio
    pin: GPIO2
    id: "sprinkler_bamboo"
    name: "Sprinkler Bamboo"
    on_turn_on: 
      then:
        - switch.turn_off: sprinkler_terrace
        - switch.turn_off: sprinkler_bed_middle
        - switch.turn_off: sprinkler_apple_tree
        - switch.turn_off: sprinkler_middle
        - switch.turn_off: sprinkler_drip
  # White Cable
  - platform: gpio
    pin: GPIO14
    id: "sprinkler_drip"
    name: "Drip Irrigation"
    on_turn_on: 
      then:
        - switch.turn_off: sprinkler_terrace
        - switch.turn_off: sprinkler_bed_middle
        - switch.turn_off: sprinkler_apple_tree
        - switch.turn_off: sprinkler_bamboo
        - switch.turn_off: sprinkler_middle
