esphome:
  name: rasensprenger
  friendly_name: Rasensprenger

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !key

ota:
  password: !pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
      static_ip: 192.168.0.0
      gateway: 192.168.0.0
      subnet: 255.255.0.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rasensprenger Fallback Hotspot"
    password: !wifi_pw

captive_portal:
    
switch:
  # Orange
  - platform: gpio
    pin: GPIO16
    id: "rasensprenger_mitte"
    name: "Rasensprenger Mitte"
    on_turn_on: 
      then:
      # Make it so that only one channe can be on at once
        - switch.turn_off: rasensprenger_terrassen
        - switch.turn_off: rasensprenger_beet_mitte
        - switch.turn_off: rasensprenger_apfelbaum
        - switch.turn_off: rasensprenger_bambus
        - switch.turn_off: tropfbewaesserung
  # Grün
  - platform: gpio
    pin: GPIO5
    id: "rasensprenger_terrassen"
    name: "Rasensprenger Terrassen"
    on_turn_on: 
      then:
        - switch.turn_off: rasensprenger_mitte
        - switch.turn_off: rasensprenger_beet_mitte
        - switch.turn_off: rasensprenger_apfelbaum
        - switch.turn_off: rasensprenger_bambus
        - switch.turn_off: tropfbewaesserung
  # Blau
  - platform: gpio
    pin: GPIO4
    id: "rasensprenger_beet_mitte"
    name: "Rasensprenger Beet Mitte"
    on_turn_on: 
      then:
        - switch.turn_off: rasensprenger_terrassen
        - switch.turn_off: rasensprenger_mitte
        - switch.turn_off: rasensprenger_apfelbaum
        - switch.turn_off: rasensprenger_bambus
        - switch.turn_off: tropfbewaesserung
  # Gelb
  - platform: gpio
    pin: GPIO0
    id: "rasensprenger_apfelbaum"
    name: "Rasensprenger Apfelbaum"
    on_turn_on: 
      then:
        - switch.turn_off: rasensprenger_terrassen
        - switch.turn_off: rasensprenger_beet_mitte
        - switch.turn_off: rasensprenger_mitte
        - switch.turn_off: rasensprenger_bambus
        - switch.turn_off: tropfbewaesserung
  # Rot
  - platform: gpio
    pin: GPIO2
    id: "rasensprenger_bambus"
    name: "Rasensprenger Bambus"
    on_turn_on: 
      then:
        - switch.turn_off: rasensprenger_terrassen
        - switch.turn_off: rasensprenger_beet_mitte
        - switch.turn_off: rasensprenger_apfelbaum
        - switch.turn_off: rasensprenger_mitte
        - switch.turn_off: tropfbewaesserung
  # Weiß
  - platform: gpio
    pin: GPIO14
    id: "tropfbewaesserung"
    name: "Tropfbewässerung"
    on_turn_on: 
      then:
        - switch.turn_off: rasensprenger_terrassen
        - switch.turn_off: rasensprenger_beet_mitte
        - switch.turn_off: rasensprenger_apfelbaum
        - switch.turn_off: rasensprenger_bambus
        - switch.turn_off: rasensprenger_mitte
